app = "mon-bot-discord-ipdlfw"
primary_region = "cdg"

[build]
builder = "paketobuildpacks/builder:base"

[env]
PORT = "8080"

[http_service]
auto_start_machines = true
auto_stop_machines = false
force_https = true
internal_port = 8080
min_machines_running = 1
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
